### PR TITLE
v1.13.0 release

### PR DESCRIPTION
**Pull request by fheinecke**
## [1.13.0] - 2024-05-30
This is the first release of this project under Gravitational management.

### Added

- Helm chart with Prometheus Operator support, pushed to GHCR (#29)
- Multiarch container images (#33)
- Images are now also pushed to GHCR, and include semver tags (#28)
- Quota limits are now overridable via the `--limit-override` parameter (#31)
- Service quota lookups are now cached (#22)
- Added SNS checks for messages published per second, topic transactions per second,
  and resource transactions per second (#23)
- A new dynamic dashboard has been added to visualize resources nearing their
  quota limits (#29)
- Added checks for KMS, Athena, EKS, and EC2 launch templates (#15)
- Added VPC checks for endpoint count, NAT gateway count, and peering
  connections per VPC (#6)

### Changed

- The `instance` label is now called `aws_resource` to avoid naming conflict
  with Prometheus' `instance` service discovery label (#35)
- Updated dependencies
- Request duration metrics will now also include `account`, `region`, and
  `aws_resource` labels (#34)
- Updated all quota descriptions to match AWS descriptions (#20)

### Fixed
- Fixed assorted quota scopes using incorrect values (#21)

### CODE REVIEW

**Review by logand22 — APPROVED** [review]
LGTM. Would be nice to have actual links in CHANGELOG but not big issue.

**Comment by fheinecke** [comment]
@logand22 happy to add them if you like. Do you know if this still adheres to https://keepachangelog.com/? The "format" is far from rigorous, but I don't see an example of this in 1.1.0.

**Comment by logand22** [comment]
> Do you know if this still adheres to https://keepachangelog.com/? The "format" is far from rigorous, but I don't see an example of this in 1.1.0.

No idea, but "_Changelogs are for humans, not machines_" to me would advocate for such a thing. Like I mentioned before I don't really care or consider it to be a blocker. Didn't realize we were strictly adhering to the linked format.

**Comment by fheinecke** [comment]
> "Changelogs are for humans, not machines" to me would advocate for such a thing

Good enough for me, added.

**Pull request merged**
